### ISSUE TITLE
OpenRGB support?

### ISSUE THREAD

**Issue by xeluxee** [tuxedocomputers/tuxedo-keyboard#102]
[OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) is a project that aims to be a universal multiplatform RGB LEDs controller for many devices, like mouses, keyboards, motherboards...

[Creating](https://gitlab.com/CalcProgrammer1/OpenRGB#contributing) a compatible controller for Clevo/Tuxedo laptops would be advantageous: it would be multiplatform thanks to OpenRGB nature and keyboard settings would be simpler to control for users, since OpenRGB provides a GUI to control keyboard colours, modes and various settings

**Comment by blueboy-tm** [comment]
Hello, use this
https://github.com/blueboy-tm/LinuxBacklightManager/

**Comment by blueboy-tm** [comment]
> [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) is a project that aims to be a universal multiplatform RGB LEDs controller for many devices, like mouses, keyboards, motherboards...
> 
> [Creating](https://gitlab.com/CalcProgrammer1/OpenRGB#contributing) a compatible controller for Clevo/Tuxedo laptops would be advantageous: it would be multiplatform thanks to OpenRGB nature and keyboard settings would be simpler to control for users, since OpenRGB provides a GUI to control keyboard colours, modes and various settings

**Comment by blueboy-tm** [comment]
> [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) is a project that aims to be a universal multiplatform RGB LEDs controller for many devices, like mouses, keyboards, motherboards...
> 
> [Creating](https://gitlab.com/CalcProgrammer1/OpenRGB#contributing) a compatible controller for Clevo/Tuxedo laptops would be advantageous: it would be multiplatform thanks to OpenRGB nature and keyboard settings would be simpler to control for users, since OpenRGB provides a GUI to control keyboard colours, modes and various settings

Hello, use this
https://github.com/blueboy-tm/LinuxBacklightManager/

**Comment by nils-van-zuijlen** [comment]
I would like to add that it may be that [the existing driver for Clevo per key keyboards](https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/Clevo-Per-Key-Keyboard) works, and that the "only" modification needed is the USB device ID.

**Comment by der-ali** [comment]
This would be the best solution, instead of implementing own client.
