### ISSUE TITLE
Simpler animations for simpler backilghts (for example, for Aura 15)

### ISSUE THREAD

**Issue by TiGR** [tuxedocomputers/tuxedo-keyboard#104]
As I understand, Aura 15 Gen 1 has simple backlight control which allows only to changing color (`color_left` parameter) and brightness for entire keyboard. So, although you can't make animations across the keyboard (such as wave), but you still can make some simpler animations, for example, when the entire keyboard pulses in single color, or when it smoothly changes colors.

Could we have something like this? Or even better, could we have support for OpenRGB as it is suggested in #102 ?

**Comment by TiGR** [comment]
Or, does it actually able to make complex animations, but it is not supported by the driver as it is [in situation with Stellaris](https://github.com/tuxedocomputers/tuxedo-keyboard/issues/103#issuecomment-913858591)?

**Comment by tuxedoxt** [comment]
Hello,

off hand I do not know if this one supports the animations. You could try to set the `mode` parameter/sysfs entry to other numbers than 0.

**Comment by TiGR** [comment]
Nothing happens when I do that.

**Comment by blueboy-tm** [comment]
Hello, use this
https://github.com/blueboy-tm/LinuxBacklightManager/

**Comment by cybik** [comment]
> Hello, use this https://github.com/blueboy-tm/LinuxBacklightManager/

Why.
