### ISSUE TITLE
Mo modes available on XMG APEX15

### ISSUE THREAD

**Issue by 3isenHeiM** [tuxedocomputers/tuxedo-keyboard#115]
Thanks for this tool, I was able to install it on my XMG APEX15 :)

However using the ``Fn`` + ``/`` to change mode, I only this sequernce : RED, GREEN, BLUE, YELLOW, PURPLE, CYAN, WHITE, OFF, and these are only static colors.

**I can't set the Breathe mode, or any dynamic one.**

**Comment by tuxedoxt** [comment]
Hello,

off hand I do not know what modes are available for that keyboard. In general the Fn key will just cycle colors even if other modes are supported.

You can try to play around with the sysfs interface in `/sys/devices/platform/tuxedo_keyboard/`.

Specifically https://github.com/tuxedocomputers/tuxedo-keyboard#mode would be relevant

**Comment by 3isenHeiM** [comment]
Thanks.

I don't find the method on how to play with these mode.

Entering the command `sudo modprobe tuxedo_keyboard mode=7` for instance didn't help...

**Comment by tuxedoxt** [comment]
You can write to the sysfs "files" directly, for example...

```
echo 7 | sudo tee /sys/devices/platform/tuxedo_keyboard/mode
```

**Comment by 3isenHeiM** [comment]
Seems that not every feature is available on my model, I cannot have dynamic mode, not left-right colors ;)

Thanks for the help anyway !
