### ISSUE TITLE
Not working with Manjaro on Infinitybook 14

### ISSUE THREAD

**Issue by petrarca-arezzo** [tuxedocomputers/tuxedo-keyboard#116]
I*m running Manjaro KDE Plasma (stable) on a Infinitybook Pro 14 Gen 6, installed `tuxedo-keyboard` from the repository (cf. screenshot) but can*t get it working:
```
sudo modprobe tuxedo_keyboard
modprobe: FATAL: Module tuxedo_keyboard not found in directory /lib/modules/5.13.19-2-MANJARO
```
![Screenshot](https://user-images.githubusercontent.com/74855438/143821314-0e0e4658-6e78-46f9-9b8c-f70cee275c2a.png)

**Comment by tuxedoxt** [comment]
Hello, please check the output of

```
dkms status
```

it needs to say installed for the booted kernel (`uname -r`).

If it doesn't you can try to manually build/install it with

```
sudo dkms install tuxedo-keyboard/3.0.9
```

or refer to any errors generated.

**Comment by George4All** [comment]
I've had a similar issue on elementary OS 6.0. Running 
`sudo make dkmsinstall`
returms
`cp -R . /usr/src/tuxedo-keyboard-3.0.9
dkms install -m tuxedo-keyboard -v 3.0.9
Error! echo
Your kernel headers for kernel 5.11.0-40-generic cannot be found at
/lib/modules/5.11.0-40-generic/build or /lib/modules/5.11.0-40-generic/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
make: *** [Makefile:43: dkmsinstall] Error 1
`

**Comment by petrarca-arezzo** [comment]
I had to install the linux headers (via pamac) and have the following now:
```
> dkms status
tuxedo-keyboard/3.0.9, 5.13.19-2-MANJARO, x86_64: installed
> uname -r
5.13.19-2-MANJARO
> cat /etc/modprobe.d/tuxedo_keyboard.conf
options tuxedo-keyboard mode=0 brightness=75 color_left=0xFFFFFF color_center=0xFFFFFF color_right=0xFFFFFF
```
Probably, I'm too dumb to see it, but I would I enable the backlight (the TCC doesn't show any option). As mentioned I installed tuxedo_keyboard via Pamac; there is no tuxedo-io, clevo-wmi, or clevo-acpi available via Pamac.

**Comment by petrarca-arezzo** [comment]
Any idea what might be the issue (or what I'm overlooking) that I can't enable the keyboard backlight?

**Comment by tuxedoxt** [comment]
There is (currently) no special driver for the keyboard backlight for your model. The Fn+space (I believe) should work anyway.

**Comment by Uhter** [comment]
Hello,
I'm not an expert but, have you see/try [this](https://wiki.archlinux.org/title/TUXEDO_InfinityBook_Pro_15v4#Function_keys) under 'Function keys' section?

**Comment by tuxedoxt** [comment]
> Hello, I'm not an expert but, have you see/try [this](https://wiki.archlinux.org/title/TUXEDO_InfinityBook_Pro_15v4#Function_keys) under 'Function keys' section?

Good point, make sure those `acpi_` parameters are **not** set.

`tuxedo-keyboard` will map the missing keys (like airplane, touchpad)

**Comment by petrarca-arezzo** [comment]
Wonderful - in the end just Fn+<space-bar> did the trick !
