### ISSUE TITLE
Backlight not working: TUXEDO Stellaris 15 - Gen3 - Ubuntu

### ISSUE THREAD

**Issue by segidev** [tuxedocomputers/tuxedo-keyboard#119]
Hello there,

i am in contact with the support for a while now but it won't solve.

I have an
- TUXEDO Stellaris 15 - Gen3 running Ubuntu 20.04.3 on kernel 5.11.0-46-generic
- `cat /sys/class/dmi/id/board_name` -> `GMxTGxx`

I purged and reinstalled `tuxedo-keyboard` (apt) multiple times. I tried to play with the config at `/etc/modprobe.d/tuxedo_keyboard.conf` using the default (after apt install) but also changing it to this:
```
options tuxedo_keyboard color=WHITE
```

Nothing happens at all (pressing `FN + Space`). I can see on the screen that the "popup" appears to toggle the Backlight but the keyboard stays dark.

On Startup it does not even blink anymore. But after installing `tuxedo-keyboard-ite` a short blink (of the keyboard in white) during startup is back. Still i can't turn it on.

Weirdly enough yesterday it magically worked after reinstalling and restarting multiple times (even with mixed colors). See this:
![Image from iOS resized](https://user-images.githubusercontent.com/28906187/149182464-f188c0c7-9a64-4945-a8d4-1d4789cfb377.jpg)

My `/etc/default/grub` looks like this:

```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.reset i8042.nomux i8042.nopnp i8042.noloop acpi_backlight=vendor"
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
```

I am really at the end of what to do.

Does anyone have a nice suggestion? :)

**Comment by tuxedoxt** [comment]
Hello,

`tuxedo-keyboard-ite` should create a :kbd_backlight interface in `/sys/class/leds`. Writing to the `brightness` control there should change the brightness up until `max_brightness`. Let's start by checking if this works.

**Comment by segidev** [comment]
Oh well that worked like a charm.

Although to be exact i did this:
- `sudo gedit /sys/class/leds/ite_8291::kbd_backlight/brightness`
- Changed from 0 to 50 (this is what is in max_brightness

Okay great. So `FN + Space` does not do anything still the lights are just on now.

How do we continue?

Thank you so far already :)

**Comment by tuxedoxt** [comment]
Great, so the driver works. The functionality of Fn+space is somewhat dependent on which environment is used. It sounds like the keyboard brightness toggle for you toggles between configured brightness and zero.

For example Gnome and KDE looks for a :kbd_backlight interface and provides a slider somewhere (usually around the power settings) to control the brightness.

Regarding "just white". Yes the driver interface is currently just brightness of white. Colors, per key configuration and standard animations are planned for a near future as settings through TCC, but alas, not yet there.

**Comment by segidev** [comment]
Ok get it, thanks

But how did i manage to have the multi colored keyboard then?

Pressing `FN + Space` changed the brightness 4 times then turned off and then repeat

It showed me it is possible but i can't remember what i did to make it work

**Comment by tuxedoxt** [comment]
Colored was probably a boot without tuxedo-keyboard-ite installed. Then whatever is shining from the boot-animation could stay.

**Comment by segidev** [comment]
I could live with that as well. But removing `ite` leads to no light at all again.

Well i will stick with white for now. Will the color mode be implemented with the ite package?

**Comment by tuxedoxt** [comment]
> Will the color mode be implemented with the ite package?

Yes, or the modules will probably be integrated into the tuxedo-keyboard module bundle package eventually.

The color features will be a combination of the driver and configurable settings in TCC.

**Comment by segidev** [comment]
Alright thank you for the information and help. Looking forward for the rainbow keyboard :)

**Comment by Uhter** [comment]
> The color features will be a combination of the driver and configurable settings in TCC.

What is TCC?

**Comment by segidev** [comment]
> > The color features will be a combination of the driver and configurable settings in TCC.
> 
> What is TCC?

Tuxedo Control Center probably?

**Comment by Uhter** [comment]
Of course. I didn't think about it.
Thanks ;)

**Comment by segidev** [comment]
@tuxedoxt 

Just quickly want to show you what's going on now.

I have the white backlight which is awesome but as you can see in the video on every startup (only after the Laptop was shutdown entirely) i have the color screen until the switch during the startup procedure, then the lights are white.

I suppose that's because the ite driver is then loaded?

Not bad but it shows me that somehow the colorful light should work also during the normal run, right?

https://www.youtube.com/watch?v=pHnFJbLZgzY

Regards

**Comment by easygater** [comment]
Thanks @segidev for taking the effort to fight for the rainbow colors. I've the same issue and really looking forward to change the colors.

**Comment by thackl** [comment]
Same issue here. "-ite" white works but no colors

**Comment by Bosper-the-Magician** [comment]
Did something change here? I also want my colored keyboard : Stellaris 17

**Comment by pescepalla** [comment]
Stellaris 17, Arch Linux: Tried to enquire about this with Tuxedo's support, and basically they recommend I install TuxedoOS. 🤷

**Comment by segidev** [comment]
Update from my side: I have actually changed to Tuxedo OS 2 (and i am very happy). It helps a lots to fix issues and with the new Tuxedo Control Panel I can set the color and brightness of my Keyboard which is then applied on the login screen.

@pescepalla @Bosper-the-Magician Did you try upgrading to Tuxedo Control Panel >= 2.0 ?

![image](https://user-images.githubusercontent.com/28906187/236121593-173f8c11-2e5b-4ca9-a6f0-7b904f69a70d.png)

**Comment by segidev** [comment]
> Thanks @segidev for taking the effort to fight for the rainbow colors. I've the same issue and really looking forward to change the colors.

Sadly no rainbow colors since now. But at least setting a color :laughing:

**Comment by pescepalla** [comment]
I've noticed the tool just now and it works! Thanks for pointing it out for me.
