### ISSUE TITLE
Expected timeline to get PR reviewed

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-keyboard#125]
What's the expected timeline to have PR reviewed?
[Mine](https://github.com/tuxedocomputers/tuxedo-keyboard/pull/105) has been sitting for about half an year with just me fixing when you made a breaking update.

**Comment by jondo** [comment]
In the meantime the discussion within the affected PR continued. This should be closed (and asked within the PR in the first place).

**Comment by brunoais** [comment]
@jondo Meh... I didn't get a direct answer but it's fine. I can close.
I'm still trying to keep up with the changes but being busy as I am, when I get an update done, there's another one to integrate into my changes. That takes away motivation, unfortunately.
