### ISSUE TITLE
source code for tuxedo-keyboard-ite Package

### ISSUE THREAD

**Issue by kjhambrick** [tuxedocomputers/tuxedo-keyboard#126]
I am running Slackware64 15.0 ons Sager NP9262M-G1 ( Clevo X170KM-G / Tuxedo Book XUX713 )
tuxedo-keyboard + tuxedo-keyboard -ite combined allow me to control my Keyboard BackLights via the Number Pad Keys.
I was considering building a Slackware Package for the two sets of Kernel Modules.
I've found the tuxedo-keyboard source on github.
And I found the tuxedo-keyboard-ite-0.2.3-1.noarch.rpm Package
Is the source for tuxedo-keyboard-ite also available ?
Thanks !
-- kjh

**Comment by fethomm** [comment]
tuxedo-keyboard-ite is in the process of being merged into tuxedo-keyboard.
