### ISSUE TITLE
TUXEDO-Pulse-15-Gen1 Fn Lock not working

### ISSUE THREAD

**Issue by dcts** [tuxedocomputers/tuxedo-keyboard#129]
I just bought a tuxedo pulse 15 gen 1 and unfortunately I cannot make the fn lock working. 

### Expected bahaviour and goal.
when pressing `fn + ESC` the function lock should be activated, meaning that for example increasing system volume should be achievable by `F3` instead of `fn + F3`. If possible I'd like to never switch back from fn lock and have that setting by default, I never use function keys, but increasing and decreasing volume/brightness is very usefull to me personally. 

### actual behavior
pressing `fn + ESC` does not activate fn lock. It seems like there is no effect.

# my system specs
![Bildschirmfoto vom 2022-06-21 00-00-19](https://user-images.githubusercontent.com/44790691/174682657-77900a4b-3e27-40d9-af06-5516e189fbae.png)

**Comment by brunoais** [comment]
There are BIOS settings about that. See if you can find one about that subject.
To reach that menu shutdown the PC, start the PC and press F2 multiple times. It should bring you to a menu. Somewhere in the tabs and options is about FN lock or swap FN. That should be what you want.
