### ISSUE TITLE
compatibility list ?

### ISSUE THREAD

**Issue by VantaxDev** [tuxedocomputers/tuxedo-keyboard#13]
it works on N150ZU?

**Comment by kaiwasaki** [comment]
Yes but you don't have all modes and this module can only control 3 areas: left, middle and right. 
But for N150ZU left changes the color of the whole keybord. Middle and right has no effect.

**Comment by VantaxDev** [comment]
thanks. it was a bit tricky the installation but I confirm it works like a charm on kernel 4.15.0-48-generic #51-Ubuntu
