### ISSUE TITLE
Driver doesn't load with secureboot enabled

### ISSUE THREAD

**Issue by Rathmox** [tuxedocomputers/tuxedo-keyboard#136]
On Fedora 36, Enabling SecureBoot prevents the modules tuxedo-keyboard and tuxedo-io from loading.

**Comment by onurbbr** [comment]
You need to sign tuxedo_keyboard module.

**Comment by Rathmox** [comment]
Ok thanks

**Comment by Rathmox** [comment]
Ok thanks
