### ISSUE TITLE
Request support: Debian 11 - Aura 15 Gen 2

### ISSUE THREAD

**Issue by stefan-niedermann** [tuxedocomputers/tuxedo-keyboard#143]
Hello there :wave: 

I have troubles getting the LEDs working. I am currently using Debian 11.5.

My first try was cloning the repository, compiling the stuff myself and `modprobe`ing it - which failed. As far as I was able to see from the logs and other issues here, the failure was caused by using UEFI and trying to `modprobe` an unsigned module.

However, I then found that the `deb` packages are also published and I added the repository as [described here](https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#). Despite using Debian and not Ubuntu I have been able to add the sources, and after an `apt update` I could see the packages and `apt install tuxedo-keyboard`.

All of this worked without any errors - however, nothing changed. I can't control the LEDs in any way. Searching other issues I also saw, that there is also [No such thing as /sys/devices/platform/tuxedo_keyboard/](https://github.com/tuxedocomputers/tuxedo-keyboard/issues/122) on my system.

Do you have any hints for me? Any information that I could provide to help you solving this riddle? :thinking: 

Thanks in advance!

**Comment by vinzv** [comment]
Please try to install tuxedo-control-center as well. This worked fine for me with Debian Sid.

Hence also this blog post by a fellow Debian user: https://www.wedesoft.de/technology/2022/02/08/tuxedo-aura-15-debian-11/
