### ISSUE TITLE
Keep parameters between boots

### ISSUE THREAD

**Issue by T-3B** [tuxedocomputers/tuxedo-keyboard#150]
Hello!

I would like to know if it is currently possible to keep the values of the parameters even after reboot. (I'm currently using the dkms build.)

From what I saw, if there is no `/etc/modprobe.d/tuxedo_keyboard.conf` then the keyboard color will be set to white and full brightness, while if the configuration file exists then it will load the settings it contains.

I would be really happy to know a way to achieve this purpose: when I poweroff my laptop with the backlight disabled, I would like it still remains after the next boot (without changing manually `/etc/modprobe.d/tuxedo_keyboard.conf` every time).

Thanks for this great tool and your time.

**Comment by tuxedoxt** [comment]
> 

Hello,

this is kind of on the way. Interface will change somewhat and persistence of settings will be possible through TCC. I'll make a note of your scenario.
