### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Quasicitizen** [tuxedocomputers/tuxedo-keyboard#153]
Using linux for two weeks, so sorry for dumb question - 
i see version 3.1.3 here, and my pc says "tuxedo-keyboard is already the newest version (3.1.2)." How do I update?

**Comment by tuxedoxt** [comment]
Hello, basically, if it's installed from repos you can just use the update functionality of your distribution and it should update tuxedo-keyboard along with everything else.
