### ISSUE TITLE
Fn Key causes lots of errors in dmesg :  atkbd serio0: Unknown key pressed

### ISSUE THREAD

**Issue by squalou** [tuxedocomputers/tuxedo-keyboard#156]
Hi,

I have a TUXEDO InfinityBook Pro 14 Gen6 Standard,
I installed tuxedo-control-center, tuxedo-keyboard, tuxedo-touchpad-switch

I'm running PopOS at the moment.

I have lots of weird messages in dmesg whenever hitting the "Fn" key.

```
[  484.505057] atkbd serio0: Unknown key pressed (translated set 2, code 0xf8 on isa0060/serio0).
[  484.505067] atkbd serio0: Use 'setkeycodes e078 <keycode>' to make it known.

```

Thing is : I did do as suggested by the message with a completely random keycode. Works fine regarding dmesg.

```
/usr/bin/setkeycodes e078 666
```

But ... it breaks the Fn F11 -> Airplane mode key.

Is there anything smarter to do ?

**Comment by bortzmeyer** [comment]
Same problem with my Pulse 14. The `setkeycodes e078 666` does not seem to produce any effect.

**Comment by develroo** [comment]
Yeah. same here on a Gen 1 Pulse 15 with Debian Testing 6.5.0-2-amd64

```
atkbd serio0: Unknown key released(translated set 2, code 0xf8 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e078<keycode>' to make it known.  
```


All the function key functions work in Gnome, so touchpad disable, aeroplane mode, keyboard backlight etc.

So it is working ok, just have this annoying dmesg warning every time the `Fn` is pressed. 

Kinda annoying that, as I hate spams in my logs.
