### ISSUE TITLE
Brightness always on maximum

### ISSUE THREAD

**Issue by Lednerb** [tuxedocomputers/tuxedo-keyboard#16]
Hello to the tuxedo team!

At the moment I have the following problem using the keyboard:
I can set a specific color and cycle through the available colors as well as turning the backlight on and off.

However, if I want to dim the light during night time etc. the brightness will always reset to the maximum.

I've tested the widget linked here #12 with the mode `wave` and the color switches the brightness as expected. It seems that it's a software problem.

(I can hit the dim button fast several times and it works but then it lights up again)

I'm using the Infinitybook 15 v4 with Ubuntu 18.04 (Gnome) and installed it with the web-fai tool with full disk encryption.

**Comment by tuxedo-computers** [comment]
Hi lednerb,
thank you for your message. At the moment the value inside the conf file acts like a "minimum-value", too.
We know about this issue and are working on it!
