### ISSUE TITLE
Could you add support to A70 Mob?

### ISSUE THREAD

**Issue by jariojose** [tuxedocomputers/tuxedo-keyboard#161]
sudo dmidecode | grep -i "product\|manufacturer"      

>   ✔  system  
> 	Manufacturer: Avell High Performance
> 	Product Name: A70 MOB
> 	Manufacturer: Avell High Performance
> 	Product Name: Avell A70 MOB
> 	Manufacturer: Avell High Performance
> 	Manufacturer: Standard
> 	Manufacturer: Standard
> 	Manufacturer: Standard
> 	Manufacturer: A-DATA Technology
> 	Module Manufacturer ID: Bank 5, Hex 0xCB
> 	Module Product ID: Unknown
> 	Memory Subsystem Controller Manufacturer ID: Unknown
> 	Memory Subsystem Controller Product ID: Unknown
> 	Manufacturer: A-DATA Technology
> 	Module Manufacturer ID: Bank 5, Hex 0xCB
> 	Module Product ID: Unknown
> 	Memory Subsystem Controller Manufacturer ID: Unknown
> 	Memory Subsystem Controller Product ID: Unknown
> 	Manufacturer: Intel(R) Corporation

Hwinfo attached .

[hwinfo.txt](https://github.com/tuxedocomputers/tuxedo-keyboard/files/10528712/hwinfo.txt)

**Comment by tuxedoxt** [comment]
Hello,

off-hand I do not know which exact model this is or if it could work or not.

General answer though, we are only able to support TUXEDO devices.
