### ISSUE TITLE
Kernel 6.2

### ISSUE THREAD

**Issue by junocomp** [tuxedocomputers/tuxedo-keyboard#165]
I have version `3.2.0` installed and I can't seem to find `brightness`, `mode`, `color_left`, `color_center` and others inside `/sys/devices/platform/tuxedo_keyboard/`

Did it change?

**Comment by tuxedoxt** [comment]
Hello,

yes, most have moved to the general `/sys/class/leds` interface (`:kbd_backlight`). Should now be reflected in the readme.
