### ISSUE TITLE
[Fn] + [space] backlight shortcut doesn't work anymore on Polaris 17 after TCC update [abandoned]

### ISSUE THREAD

**Issue by Uhter** [tuxedocomputers/tuxedo-keyboard#169]
Hello,

After update to Tuxedo Control Center v2.0.2, Keyboard Backlight tool appeared and work well but **[Fn] + [space] backlight shortcut doesn't work anymore**: nothing happens when I use it :(

Configuration:

- TUXEDO Polaris 17 AMD Gen3
- BIOS: N.1.50A12
- EC: 1.32.29
- Manjaro Xfce
- kernel 6.2.8-1 and headers 6.2.8-1
- TTC 2.0.2-1
- Tuxedo keyboard dkms 3.2.1-1
- lsmod | grep -E "clevo|tuxedo" :
```clevo_wmi              20480  0
wmi                    45056  7 video,uniwill_wmi,clevo_wmi,asus_wmi,wmi_bmof,mxm_wmi,nouveau
tuxedo_io              24576  0
tuxedo_keyboard        77824  3 tuxedo_io,uniwill_wmi,clevo_wmi
sparse_keymap          16384  2 asus_wmi,tuxedo_keyboard
led_class_multicolor    16384  1 tuxedo_keyboard
```

What can I do?

**Comment by tuxedoxt** [comment]
Hello,

first, make sure you reboot once after upgrade and try again.

Otherwise. Fn+backlight key(s) now trigger the usually used key events upon which the WM usually reacts. Last I checked Xfce does not implement all of these. I don't know the current state.

**Comment by Uhter** [comment]
Hello @tuxedoxt,

So, this is not a Tuxedo/TCC bugs?

If I understand correctly, I have to assign a command to a Xfce shortcut? 
I know how to do, but what is this command/script?

**Comment by Uhter** [comment]
Thanks @tuxedoxt but I failed to fix it this way. But… 

[Fn] + [space] works again since I installed kernel 6.3.0-1 and upgraded Tuxedo Control Center to 2.0.5 (but I can't change keyboard color because "_Your device has no keyboard backlight or is not (yet) supported by this control interface._").

I give up.
I think Polaris 17 + Manjaro don't make a good marriage.
