### ISSUE TITLE
Possibility to disable all keyboard backlight, no fan curve business

### ISSUE THREAD

**Issue by jellelicht** [tuxedocomputers/tuxedo-keyboard#170]
I'd like to turn off all LED backlight to conserve battery charge. Whenever I load tuxedo_keyboard, I seem to get messed up fan curves as well, and they start blowing very loudly anytime I click a link in my browser.

My current workaround is to boot my laptop, close it to suspend it, and open it again so all backlights are disabled (probably a bug as well, and makes me think of [that one XKCD](https://xkcd.com/1172/)) EDIT: without any tuxedo_* kernel modules being loaded, that is.

Is it somehow possible to not change anything about my fan curves, but just disable the LEDs? I'm not currently running any fan curve daemon, nor am I interested in doing so, as I really enjoy the default behavior of my system w.r.t. fan curves.

**Comment by brunoais** [comment]
What's your laptop?

**Comment by tuxedoxt** [comment]
Hello,

check TCC => settings => global profile settings. You can individually disable fan control and leave kbd backlight control on.

**Comment by jellelicht** [comment]
> What's your laptop?

InfinityBook S15

> Hello,
> 
> check TCC => settings => global profile settings. You can individually disable fan control and leave kbd backlight control on.

I’m not running TCC, and won’t be able to on my distro, so ideally there will just be a (tuxedo_io?) kernel module parameter that disables anything having to do with fan curves.
