### ISSUE TITLE
Backlight on Suse Tumbleweed is not working

### ISSUE THREAD

**Issue by schrapm3** [tuxedocomputers/tuxedo-keyboard#173]
Hi there,

the backlight on current Tumbleweed is not working although the module seems to be loading:

[    5.361621] tuxedo_keyboard: loading out-of-tree module taints kernel.
[    5.361658] tuxedo_keyboard: module verification failed: signature and/or required key missing - tainting kernel
[    5.362464] tuxedo_keyboard: module init
[    7.215943] input: TUXEDO Keyboard as /devices/platform/tuxedo_keyboard/input/input33

Any ideas ?

**Comment by temirg** [comment]
@schrapm3: please check following:
TCC dashboard => Tools => Keyboard backlight (or similar in English) => brightness: 0% ?

Regards, temirg.

**Comment by schrapm3** [comment]
Hi,

tried with Arch Linux on another SSD with the same result. Dmesg shows:

[    1.370437] tuxedo_keyboard: loading out-of-tree module taints kernel.
[    1.370487] tuxedo_keyboard: module verification failed: signature and/or required key missing - tainting kernel
[    1.371454] tuxedo_keyboard: module init
[    2.560862] input: TUXEDO Keyboard as /devices/platform/tuxedo_keyboard/input/input10

In TCC it says:

![grafik](https://user-images.githubusercontent.com/49118602/230778036-fa80bdc3-7d6f-44a6-bac2-6d076780057a.png)

**Comment by temirg** [comment]
Possible the reinstall would help:
zypper in -f tuxedo-keyboard tuxedo-control-center
/usr/libexec/dkms/dkms_autoinstaller start $(uname -r)
reboot

**Comment by temirg** [comment]
A tuxedo device?

**Comment by tuxedoxt** [comment]
Hello,

which device do you have?

**Comment by groenator** [comment]
Hi, 

I am using Stellaris 16 gen 5 and I have the same issue. The backlight is not available on TW. 

The control center shows this:
![Screenshot_20230724_230845](https://github.com/tuxedocomputers/tuxedo-keyboard/assets/5445030/198fa2e5-17b9-4a35-aa4e-33ba53b9badd)

Installed version:
![Screenshot_20230724_231033](https://github.com/tuxedocomputers/tuxedo-keyboard/assets/5445030/368f53df-f9c8-40d7-8f02-bdf3c29e4fb4)

I run the command above and I got the following error:

```
user@tuxedo:~> sudo zypper in -f tuxedo-keyboard tuxedo-control-center /usr/libexec/dkms/dkms_autoinstaller start $(uname -r)
Loading repository data...
Reading installed packages...
Forcing installation of 'tuxedo-keyboard-3.2.8-1.noarch' from repository 'TUXEDO'.
Forcing installation of 'tuxedo-control-center-2.0.8-1.x86_64' from repository 'TUXEDO'.
'6.4.3-1-default' not found in package names. Trying capabilities.
No provider of '6.4.3-1-default' found.
'/usr/libexec/dkms/dkms_autoinstaller' not found in package names. Trying capabilities.
No provider of '/usr/libexec/dkms/dkms_autoinstaller' found.
'start' not found in package names. Trying capabilities.
No provider of 'start' found.
Resolving package dependencies...

The following 2 packages are going to be reinstalled:
  tuxedo-control-center tuxedo-keyboard

**Comment by groenator** [comment]
Installing the tuxedo-keyboard-ite package worked. The backlight is working on TW.
