### ISSUE TITLE
modprobe.d file not working 

### ISSUE THREAD

**Issue by osho741** [tuxedocomputers/tuxedo-keyboard#177]
I have the following in the modprobe.d file and it does not seem to be working.  I am trying to get the pc to start with the lights a certain color on boot:

tuxedo_keyboard mode=0 color_left=0xFF0000 color_center=0xFF0000 color_right=0xFF0000

this is in a file called tuxedo_keyboard.conf  

If I am doing something wrong please let me know. 

this is a pagolin 11 running fedora.

**Comment by Matombo** [comment]
With tuxedo-keyboard 3.2.0 the module parameters got removed and replaced with a /sys/class/leds/*kbd_backlight* interface.
tuxedo-control-center now has controls for keyboard backlight and restores the previous value on reboot.
