### ISSUE TITLE
Not working for latest kernel

### ISSUE THREAD

**Issue by alwzying** [tuxedocomputers/tuxedo-keyboard#18]
`Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
make -j8 KERNELRELEASE=5.0.0-16-generic -C . KDIR=/lib/modules/5.0.0-16-generic/build...
Signing module:
 - /var/lib/dkms/tuxedo_keyboard/1/5.0.0-16-generic/x86_64/module/tuxedo_keyboard.ko
Corrupted signature list
Secure Boot not enabled on this system.
cleaning build area...(bad exit status: 2)
`

**Comment by vrga** [comment]
it worked just fine for me. you need to run 
```dkms install -m tuxedo_keyboard -v 1```

**Comment by vinzv** [comment]
Should be fixed with recent versions. Thanks for reporting!
