### ISSUE TITLE
Stellaris 16 Gen5 RGB/Brightness

### ISSUE THREAD

**Issue by ghe0** [tuxedocomputers/tuxedo-keyboard#188]
The Fn+Space key on the Stellaris 16 Gen6 can toggle only between 0% and 100% brightness. I actually didn't know my keyboard has RGB colors and it can also adjust the brightness of the keyboard till I found the extended menu in the Control Center. Even if you set the brightness of the keyboard to 5%, hitting the hotkey 3 times will end up get the brightness back to 100%, which is far too bright if the light in your room is dark.

It would be 100% worth it (pun intended) for this specific keyboard to allow the Fn+Space to offer any of the following features:
- remember the level of brightness set via control center instead of toggling between 0% and 100%
- randomize keyboard color
- gradually increase brightness
- open keyboard setup in Control Center instead of just toggling stuff

If this is easier to setup through bash scripts or some KDE, I am all ears.

**Comment by tuxedoxt** [comment]
Hello,

currently we leave brightness up to the system. As far as I remember at least KDE default behaviour is to toggle between 0 and 100%. Theoretically this part could be replaced. Allowing the toggle key to be configured to do other things I can forward as suggestion.
