### ISSUE TITLE
broken make by commit on 10 July " Makefile: Remove incorrect and suprefluous KDIR variable definition "

### ISSUE THREAD

**Issue by lucamp** [tuxedocomputers/tuxedo-keyboard#19]
Hi,
as commented by user @scitor the commit release on 10 July 2019 named "Makefile: Remove incorrect and suprefluous KDIR variable definition" broke the making process as described in the guidelines giving the above error.

> ~/tuxedo-keyboard# make clean
> make -C M=/home/luca/tmp/tuxedo-keyboard clean
> make[1]: *** M=/home/luca/tmp/tuxedo-keyboard: No such file or directory. Stop.
> make: *** [Makefile:11: clean] Error 2

For everyone looking for a solution just revert back the file "makefile" as it was before, so delete the line number 6 and the result must be as:

```
obj-m := ./src/tuxedo_keyboard.o
tuxedo_tuxedo-objs := ./src/tuxedo_keyboard.o

PWD := $(shell pwd)
KDIR := /lib/modules/$(shell uname -r)/build

all:
	make -C $(KDIR) M=$(PWD) modules
clean:
	make -C $(KDIR) M=$(PWD) clean
install:
	make -C $(KDIR) M=$(PWD) modules_install
dkmsadd:
	cp -R . /usr/src/tuxedo_keyboard-1
	dkms add -m tuxedo_keyboard -v 1

dkmsremove:
	dkms remove -m tuxedo_keyboard -v 1 --all
	rm -rf /usr/src/tuxedo_keyboard-1
```

**Comment by tuxedoxt** [comment]
Hello, thank you for the notice.
KDIR has been reintroduced in the Makefile and the make commands should now work as before.
