### ISSUE TITLE
Missing media keys

### ISSUE THREAD

**Issue by sQVe** [tuxedocomputers/tuxedo-keyboard#193]
Hey, 👋

I might very well be missing something obvious, but I cannot, for the life of me, get the <kbd>Fn</kbd> + <kbd>F1</kbd> to <kbd>F12</kbd> to trigger the correct media key. 

My system is running Arch Linux with `tuxedo-control-center-bin` and `tuxedo-keyboard-dkms` installed from the AUR. When running `xev` and pressing  <kbd>Fn</kbd> + <kbd>F5</kbd> it doesn't output `XF86AudioMute` like my other computers. 

These are the media codes I want to use (and use in `i3wm`):
```
# Media based bindings.
bindsym XF86AudioLowerVolume exec $volume-down
bindsym XF86AudioMicMute exec $microphone-toggle
bindsym XF86AudioMute exec $volume-toggle
bindsym XF86AudioNext exec $music-next
bindsym XF86AudioPlay exec $music-toggle
bindsym XF86AudioPrev exec $music-prev
bindsym XF86AudioRaiseVolume exec $volume-up
bindsym XF86MonBrightnessDown exec $brightness-down
bindsym XF86MonBrightnessUp exec $brightness-up
bindsym XF86PowerOff exec $menu-state
```

Any guidance on how to get this to work would be greatly appreciated! 🙏🏼

**Comment by h3n3b0sch** [comment]
Hello,

I really would like to hear answers to this issue. I have a same kind of problem; I'm trying to get the keys working on DWM. Running the Tuxedocomputers Xubuntu everything works fine but when I'm switching to the DWM window manager I can't get it to work. 

Anyone who can help us out?

With kind regards,
h3n3
