### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jellelicht** [tuxedocomputers/tuxedo-keyboard#21]
While we are waiting for #17, it would be nice to tag a recent (working) version as a release version. This would allow people to easily create reproducible custom packages for their distro, which would already make one person very happy (me :smile: ).

**Comment by jellelicht** [comment]
It would be really nice to get some form of acknowledgement (positive or negative) to this issue. Thanks in advance

**Comment by tuxedoxt** [comment]
Releases will (at least from now on) be tagged and the latest can be found by checking out the `release` branch.
