### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by enescaglayan** [tuxedocomputers/tuxedo-keyboard#25]
i did everything explained in readme.md its not actually working for me.
i am using a clevo computer

heres my terminal log: https://paste.ee/p/P0qAw

**Comment by brokenax3** [comment]
Have you tried adding
`tuxedo_keyboard`
to /etc/modules-load.d

**Comment by enescaglayan** [comment]
theres even no folder named `tuxedo_keyboard` and if you mean adding it to here it does not exist.

quote from my terminal log
> modprobe: ERROR: could not insert 'tuxedo_keyboard': No such device

**Comment by brokenax3** [comment]
Sorry I meant adding the line to the conf file in /etc/modules-load.d

**Comment by enescaglayan** [comment]
> Sorry I meant adding the line to the conf file in /etc/modules-load.d

I will try that later thanks for reply :)
