### ISSUE TITLE
Airplane key is not part of this project

### ISSUE THREAD

**Issue by Zeroneca** [tuxedocomputers/tuxedo-keyboard#31]
Is there any plan in inluding the functionality of the airplane hotkey in this project? It is implemented in clevo-xsm-wmi and tuxedo-wmi.

I could include it in the next weeks if nobody's already working on this.

**Comment by startedfr0mtheb0tt0m** [comment]
Do you have 

acpi_os_name=Linux acpi_osi= acpi_backlight=vendor 

in your Grub Configuration?

**Comment by Zeroneca** [comment]
I'm not using grub2. Why is everyone expecting that? The airplane hotkey is working with clevo-xsm-wmi/tuxedo-wmi so I thought those are some special wmi calls not implemented in the linux kernel.

But I try those parameters out in a sec
