### ISSUE TITLE
Auto-Off (Timed)

### ISSUE THREAD

**Issue by autotechmusic** [tuxedocomputers/tuxedo-keyboard#32]
Greetings,

In Windows, my laptop can shut off the LED keyboard light after a set time (5 min - 20 min) with the control center software.

Does this module have an auto-off setting that we can insert into the conf file.  Please adivse.
Thanks.

AT

**Comment by tuxedoxt** [comment]
> Greetings,
> 
> In Windows, my laptop can shut off the LED keyboard light after a set time (5 min - 20 min) with the control center software.
> 
> Does this module have an auto-off setting that we can insert into the conf file. Please adivse.
> Thanks.
> 
> AT

Hello, this is currently not supported but the feature request is relatively often asked for and duly noted ;)

**Comment by autotechmusic** [comment]
Looking forward to seeing that in action.

Cheers
