### ISSUE TITLE
color_left effects whole keyboard

### ISSUE THREAD

**Issue by chriscamacho** [tuxedocomputers/tuxedo-keyboard#41]
I have a N150CU laptop

To be fair this might not be a bug ?
color_left seems to effect the whole keyboard, right and center have no effect

might it be that with this model of laptop that only has left wired to the whole keyboard for all I know, but thought it might be worth reporting... (if only so you get a handle on how the chip is used in the wild!)

**Comment by StevenSeifried** [comment]
This model has a single-zone keyboard illumination. As it is not a multi-zone keyboard illumination the parameters in "color_center", "color_right" and "color_extra" are ignored.

**Comment by chriscamacho** [comment]
If its hardware that's already known of...
