### ISSUE TITLE
Compatible with N141CU?

### ISSUE THREAD

**Issue by Bulmer** [tuxedocomputers/tuxedo-keyboard#43]
I have a new model Clevo ultrabook N141CU and am having issues getting any response with the hotkeys. Theres no real errors in the logs and it seems to be installing fine, however I can't seem to find any process running. Is there supposed to be a process running? Is there any issues with running this module on a smaller keyboard layout (without a numpad)?

**Comment by freechelmi** [comment]
N141CU does not need this to have the control of the backlight through its dedicated key.
