### ISSUE TITLE
Cannot set module parameters

### ISSUE THREAD

**Issue by ClementMassonnaud** [tuxedocomputers/tuxedo-keyboard#48]
Hello,
I am running Arch Linux 5.6.8 on a TUXEDO Book BC1510
I successfully built the module via the DKMS route.
It works great with the keyboard shortcuts, I can set keyboard backlight on/off, switch colours, and set brightness level.

However I cannot set any parameter using the command line. Neither with modprobe nor Sysfs.

For instance running:
`sudo modprobe tuxedo-keyboard color_left=ff0000`
doesn't do anything

Modifying the `/etc/modprobe.d/tuxedo_keyboard.conf` doesn't do anything either.

Here is the output of `modinfo tuxedo-keyboard`:
`filename:       /lib/modules/5.6.8-arch1-1/kernel/lib/tuxedo_keyboard.ko.xz`
`alias:          wmi:ABBC0F6D-8EA1-11D1-00A0-C90629100000`
`alias:          wmi:ABBC0F6B-8EA1-11D1-00A0-C90629100000`
`version:        2.0.2`
`license:        GPL`
`description:    TUXEDO Computers Keyboard Backlight Driver`
`author:         Christian Loritz / TUXEDO Computers GmbH <tux@tuxedocomputers.com> `
`srcversion:     C5E4B6AFD14E0F3F229FE9C`
`depends:        wmi`
`retpoline:      Y`
`name:           tuxedo_keyboard`
`vermagic:       5.6.8-arch1-1 SMP preempt mod_unload` 
`parm:           color_left:Color for the Left Region (uint)`
`parm:           color_center:Color for the Center Region (uint)`
`parm:           color_right:Color for the Right Region (uint)`
`parm:           color_extra:Color for the Extra Region (uint)`
`parm:           mode:Set the keyboard backlight blinking pattern`
`parm:           brightness:Set the Keyboard Brightness`
`parm:           state:Set the State of the Keyboard TRUE = ON | FALSE = OFF (bool)`

Tell me if you need more information
Thank you

**Comment by tuxedoxt** [comment]
Hello, I believe specified colors need to be prefixed with 0x
Please have a look at the readme for more details and example .conf file.
