### ISSUE TITLE
Feature request for frontend scripts

### ISSUE THREAD

**Issue by fethigurcan** [tuxedocomputers/tuxedo-keyboard#49]
Hello,

Please check out my gnome extension to work with tuxedo-keyboard : https://github.com/fethigurcan/tuxedo-keyboard-gnome-extension

If you would add the udev rule at the project which gives write permission to others to set brightness and colors at your package or give us other proper way to do this. It will be more simple to write this kind of frontends :) 

thanks

**Comment by Cyrille37** [comment]
Other frontend applications:
- https://github.com/encarsia/tuxedo-backlight-control
- https://github.com/leaanthony/tuxedo-keyboard-ui

**Comment by Cyrille37** [comment]
Thanks a lot to share your work. Nice to have the udev rules file :-)
