### ISSUE TITLE
changing keyboard brightness does not work on InfinityBook Pro 14 v5

### ISSUE THREAD

**Issue by mschiff** [tuxedocomputers/tuxedo-keyboard#50]
Using `Fn+F4` to change the brightness is always working. Even without the module being loaded. But testing with `xev` no KeyPressed-Events are being emitted to the system.

Loading the module works fine:
```
~ # dmesg
[56901.424667] tuxedo_keyboard: Model 'TUXEDO' found
[56901.549661] tuxedo_keyboard: set_mode on CUSTOM
[56901.592072] tuxedo_keyboard: Set brightness on 255
[56901.600897] tuxedo_keyboard: Set keyboard enabled to: 1
[56901.609038] input: TUXEDO Keyboard as /devices/platform/tuxedo_keyboard/input/input47
~ # cat /sys/devices/platform/tuxedo_keyboard/brightness
255
~ #
```

After that I can see events using `xev`:

```
KeyPress event, serial 41, synthetic NO, window 0xa200001,
    root 0x1a1, subw 0x0, time 57227841, (155,257), root:(1026,736),
    state 0x0, keycode 238 (keysym 0x1008ff05, XF86KbdBrightnessUp), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 41, synthetic NO, window 0xa200001,
    root 0x1a1, subw 0x0, time 57227841, (155,257), root:(1026,736),
    state 0x0, keycode 238 (keysym 0x1008ff05, XF86KbdBrightnessUp), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

But the module fails to set the brighness in any way. Trying to echo any value to the brighness file will not change anything and the value stays at 255.
Also using something like `xdotool key XF86KbdBrightnessUp` does not work.

Would be nice to have this fixed so the keyboardlight can be turned on and off after booting or based on daytime or even sunrise/sunset times.

**Comment by tuxedoxt** [comment]
Backlight control through the module is currently only supported on RGB keyboards where it does not have direct hardware support. Control of the plain white variants is planned however. As is proper brightness linux driver for better integration.

As for the output, the module is reporting the internal state whether there is a driver or not. (Needs better hardware detection among other things.)
