### ISSUE TITLE
Why is this still 2.0.5 but rpm.tuxedocomputers.com/opensuse/15.2/noarch/tuxedo-keyboard-2.0.6-1.noarch.rpm ???

### ISSUE THREAD

**Issue by Zappo-II** [tuxedocomputers/tuxedo-keyboard#55]
Please Clarify:

| Why is this still 2.0.5 but rpm.tuxedocomputers.com/opensuse/15.2/noarch/tuxedo-keyboard-2.0.6-1.noarch.rpm ???

**Comment by tuxedoxt** [comment]
Source repo update was a little bit behind, should now all be there, enjoy :)
