### ISSUE TITLE
Q: where does tuxedo-keyboard store logs? (like TUXEDO_ERROR)

### ISSUE THREAD

**Issue by webketje** [tuxedocomputers/tuxedo-keyboard#57]
For an issue on tuxedo-backlight-control, [a user seems to have an incomplete SysFs installation](https://github.com/webketje/tuxedo-backlight-control/issues/10).
Looking at the code of this repo there should be a trace of issues with the message `Sysfs attribute file creation failed for state`..
Where can it be found? `/var/log/dmesg/tuxedo_keyboard`? journalctl?

**Comment by tuxedoxt** [comment]
Hello, the messages info/err/debug etc are normal kernel log messages see: https://www.kernel.org/doc/html/latest/core-api/printk-basics.html. So depending on what on the system is storing these is where they can be found. `journalctl` does it as far as I know, depending on system it also saves previous boots.

**Comment by webketje** [comment]
Ok thanks closing this issue
