### ISSUE TITLE
libkmod: kmod_config_parse: /lib/modprobe.d/tuxedokeyboard.conf line 1: ignoring bad line starting with 'tuxedo_keyboard'

### ISSUE THREAD

**Issue by nigelwarning** [tuxedocomputers/tuxedo-keyboard#58]
After updating the AUR package I get this warning when running sudo mkinitcpio -P

libkmod: kmod_config_parse: /lib/modprobe.d/tuxedokeyboard.conf line 1: ignoring bad line starting with 'tuxedo_keyboard'

I don't know if it is something bad or not.

**Comment by tuxedoxt** [comment]
Since it's the AUR I do not know, @StevenSeifried ?

**Comment by StevenSeifried** [comment]
Hey @nigelwarning 

i will update the AUR Package later that day and remove the `/usr/lib/modprobe.d/tuxedokeyboard.conf` line in the PKGBUILD.

**Comment by StevenSeifried** [comment]
@nigelwarning AUR Package is updated. 
@tuxedoxt I think the issue can be closed
