### ISSUE TITLE
Crashing when mode= is changed

### ISSUE THREAD

**Issue by ThatComputerKid** [tuxedocomputers/tuxedo-keyboard#70]
When I set mode to mode=1 in /etc/modprobe.d/tuxedo_keyboard.conf my computer begins freezing every 10 minutes or so, with the only solution being a hard reboot. I am running Fedora KDE 33 on a Aura 15. Thanks in advance.

**Comment by tuxedoxt** [comment]
Hello, this sounds weird. Tested it quickly but could not reproduce. Maybe coincidence, something unrelated?

**Comment by tuxedoxt** [comment]
I'll close this for now due to inactivity. Feel free to answer/reopen anyway if there's an update.
