### ISSUE TITLE
Can it be used in Debian with 5.9 kernel?

### ISSUE THREAD

**Issue by MarcusFloeser** [tuxedocomputers/tuxedo-keyboard#79]
I tried to compile modules for my Netrunner XUL system which is based on Debian Buster. But nothing happens after running "make". Modules were not found.

Any idea?

**Comment by tuxedoxt** [comment]
Since it's debian did you try our debian package from our repo, it would be the easiest way. Prereq dkms.

Which device do you have?

**Comment by MarcusFloeser** [comment]
I have a AURA 15 Gen1

**Comment by tuxedoxt** [comment]
Ah yeah this should work fine.

https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#

**Comment by MarcusFloeser** [comment]
y. works fine now. 
Thx
