### ISSUE TITLE
Keyboard backlight animations doesn't seems to work on Aura 15

### ISSUE THREAD

**Issue by MaximeChretien** [tuxedocomputers/tuxedo-keyboard#85]
Hi,

I have a Tuxedo Aura 15 since a few weeks and only fixed color mode seems to work. I have installed tuxedo-keyboard on Manjaro (both repo one (3.0.4) and AUR one (3.0.5)) but when I change the keyboard mode (breathe, wave, ...) in sysfs nothing happens, it just stays with the fixed color. I also quickly tested that on the preinstalled ubuntu system before reinstalling everything and it wasn't working either.

I can change the color of the whole keyboard using color_left while color_right, color_center and color_extra don't change anything so I guess the keyboard only supports one color at a time. (?)

An interesting thing is that the keyboard does have some animation when I'm in the UEFI settings or while booting before I reach the graphical UI (before the kernel loads the module maybe ?), it cycles through colors.

Another thing is that if I look into dmesg I can see that the driver is aware of the mode change since there are some `tuxedo_keyboard: set_mode on WAVE` lines appearing.

So maybe there is some kind of problem with the kernel driver or the keyboard doesn't support all modes or mine have a problem. Anyway that's not a big problem but since I didn't found anything about that online I wanted to know if something could be done about that.

Have a nice day !

**Comment by tuxedoxt** [comment]
Hello,

I had a quick look in the windows Clevo Control Center. There are no animations for this device/keyboard. I agree it's curious that they still put a boot animation ^^

As for the driver saying stuff. This part of the driver is a little bit too verbose and still lacks good device recognition. Basically it tries to set it as if it was talking to an animating keyboard backlight but there is no response so it doesn't know if it succeeded or not.
