### ISSUE TITLE
[Feature Request] Support for white backlight keyboards

### ISSUE THREAD

**Issue by SimoFiuz** [tuxedocomputers/tuxedo-keyboard#87]
As the title states: support for backlight control for white-lit only keyboards would be great. For boards/chassis like the Clevo NV40MB.

**Comment by mhx** [comment]
+1, I was spending the last few hours wondering why there were no controls at all in `/sys/devices/platform/tuxedo_keyboard` for my InfinityBook Pro 14 Gen6.
