### ISSUE TITLE
Apply changes in "tuxedo_keyboard.conf" immediately without reboot

### ISSUE THREAD

**Issue by roundoutandabout** [tuxedocomputers/tuxedo-keyboard#92]
According to the [article](https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Installation-of-keyboard-drivers-for-TUXEDO-Computers-models-with-RGB-keyboard-.tuxedo) from Tuxedo website, to apply changes in `/etc/modprobe.d/tuxedo_keyboard.conf` without reboot, it is needed to remove and load the module:
`$ sudo rmmod tuxedo_keyboard`
`$ sudo modprobe tuxedo_keyboard`

However the first command gives an error:
`rmmod: ERROR: Module tuxedo_keyboard is in use by: clevo_acpi tuxedo_io clevo_wmi`

I think the right way will be to remove the modules `clevo_acpi`, `tuxedo_io`, `clevo_wmi` first and then `tuxedo_keyboard`.

**Comment by tuxedoxt** [comment]
Hello,

yes, you are correct. The article seems to need an update.

For reference here's a link to one install script that does just what you describe.

https://github.com/tuxedocomputers/tuxedo-keyboard/blob/master/deb/module-name/DEBIAN/postinst#L59-L68

**Comment by roundoutandabout** [comment]
Thanks,
The issue can be closed.
