### ISSUE TITLE
Driver options for tuxedo_keyboard_ite

### ISSUE THREAD

**Issue by fedevx** [tuxedocomputers/tuxedo-keyboard#96]
Hello!

I'm looking at changing the keyboard's back-light color. I installed tuxedo_keyboard_ite and I can see the ite_8291 module was loaded.

Looking at the source, it seems the driver supports animation modes, different colors and per key control (?).

is there any documentation or somewhere I could read about the supported options? Unlike tuxedo-keyboard, there is no conf file for the ite driver.

Thanks!

**Comment by Makotophoto** [comment]
You can find some hint on the following page :
[Installation-of-keyboard-drivers-for-TUXEDO-Computers-models-with-RGB-keyboard-.tuxedo](https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Installation-of-keyboard-drivers-for-TUXEDO-Computers-models-with-RGB-keyboard-.tuxedo)
But they doesn't say how to control per-key backlight.
